name: Deploy Flask to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ostap/flaskapp || git clone https://github.com/USERNAME/REPO.git flaskapp && cd flaskapp
            git pull origin main
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp